// draw.js
import * as THREE from "three";
import { Daydream } from "./driver.js";
import { Dot, angleBetween, sphericalToPixel } from "./geometry.js";
import { G as g } from "./geometry.js";

/**
 * Creates a brush effect using a square wave for dotted drawing.
 * @param {THREE.Color} color - The base color of the brush.
 * @param {number} freq - The frequency of the square wave pattern.
 * @param {number} dutyCycle - The duty cycle (on time) of the square wave [0, 1].
 * @param {number} phase - The phase shift of the square wave.
 * @param {number} t - The position along the path (time parameter).
 * @returns {THREE.Color} The resultant color multiplied by the square wave value.
 */
export function dottedBrush(color, freq, dutyCycle, phase, t) {
  let r = squareWave(0, 1, freq, dutyCycle, phase)(t);
  return color.multiplyScalar(r);
}

/**
 * Represents a path composed of connected points on the sphere.
 */
export class Path {
  /**
   * @param {THREE.Vector3} initialPos - The starting position of the path.
   */
  constructor(initialPos) {
    this.points = [initialPos];
  }

  /**
   * Collapses the path to only the last point.
   */
  collapse() {
    this.points = [this.points[this.points.length - 1]];
  }

  /**
   * Gets the number of points in the path.
   * @returns {number} The length of the path.
   */
  length() {
    return this.points.length;
  }

  /**
   * Appends a line segment between two vectors to the path.
   * @param {THREE.Vector3} c1 - The start vector.
   * @param {THREE.Vector3} c2 - The end vector.
   * @param {boolean} [longWay=false] - If true, take the longer arc.
   * @param {Function} [easingFn=(t) => t] - An unused easing function (retained for signature).
   * @returns {Path} The path instance.
   */
  appendLine(c1, c2, longWay = false, easingFn = (t) => t) {
    if (this.points.length > 0) {
      this.points.pop();
    }
    this.points = this.points.concat(
      drawLine(c1, c2, (v) => undefined, 0, 1, longWay)
        .map((d) => d.position));
    return this;
  }

  /**
   * Appends a segment generated by a plotting function.
   * @param {Function} plotFn - Function that returns a vector based on a domain parameter t.
   * @param {number} domain - The range of the input parameter for plotFn.
   * @param {number} samples - The number of points to sample.
   * @param {Function} [easingFn=(t) => t] - The easing function to apply to the input parameter.
   * @returns {Path} The path instance.
   */
  appendSegment(plotFn, domain, samples, easingFn = (t) => t) {
    if (this.points.length > 0) {
      this.points.pop();
    }
    for (let t = 0; t < samples; t++) {
      this.points.push(plotFn(easingFn(t / samples) * domain));
    }
    return this;
  }

  /**
   * Gets a point on the path based on a normalized parameter t.
   * @param {number} t - Normalized position along the path [0, 1].
   * @returns {THREE.Vector3} A clone of the point at the given position.
   */
  getPoint(t) {
    let i = Math.floor(t * (this.points.length - 1));
    return this.points[i].clone();
  }
}

/**
 * Represents a path defined by a single procedural function.
 */
export class ProceduralPath {
  /**
   * @param {Function} pathFn - Function that takes a parameter t [0, 1] and returns a THREE.Vector3.
   */
  constructor(pathFn) {
    this.f = pathFn;
  }

  /**
   * Gets a point on the path.
   * @param {number} t - Normalized position along the path [0, 1].
   * @returns {THREE.Vector3} The point on the path.
   */
  getPoint(t) {
    return this.f(t);
  }
}

/**
 * Draws a single dot at a given vector.
 * @param {THREE.Vector3} v - The vector position (normalized).
 * @param {Function} colorFn - Function to determine the color (takes vector and t=0).
 * @returns {Dot[]} An array containing a single Dot.
 */
export const drawVector = (v, colorFn) => {
  return [new Dot(new THREE.Vector3(...v.toArray()).normalize(), colorFn(v, 0))];
}

/**
 * Draws a sequence of points along a Path object.
 * @param {Path|ProceduralPath} path - The path object.
 * @param {Function} colorFn - Function to determine the color (takes normalized time t).
 * @returns {Dot[]} An array of Dots along the path.
 */
export const drawPath = (path, colorFn) => {
  let r = [];
  for (let t = 0; t < path.length(); t++) {
    r.push(new Dot(path.getPoint(t / path.length()), colorFn(t)));
  }
  return r;
}

/**
 * Draws a geodesic line (arc) between two vectors on the sphere.
 * @param {THREE.Vector3} v1 - The start vector.
 * @param {THREE.Vector3} v2 - The end vector.
 * @param {Function} colorFn - Function to determine the color (takes vector).
 * @param {number} [start=0] - Starting angle for drawing the line arc.
 * @param {number} [end=1] - Ending multiplier for the total arc angle.
 * @param {boolean} [longWay=false] - If true, draws the longer arc.
 * @returns {Dot[]} An array of Dots forming the line.
 */
export const drawLine = (v1, v2, colorFn, start = 0, end = 1, longWay = false) => {
  let dots = []
  let u = v1.clone();
  let v = v2.clone();
  let a = angleBetween(u, v);
  let w = new THREE.Vector3();
  if (Math.abs(a) < 0.0001) {
    return [new Dot(u, colorFn(u, 1))];
  } else if (Math.abs(Math.PI - a) < 0.0001) {
    if (Math.abs(v.dot(Daydream.X_AXIS)) > 0.9999) {
      w.crossVectors(u, Daydream.Y_AXIS).normalize();
    } else {
      w.crossVectors(u, Daydream.X_AXIS).normalize();
    }
  } else {
    w.crossVectors(u, v).normalize();
  }

  if (longWay) {
    a = 2 * Math.PI - a;
    w.negate();
  }

  if (start != 0) {
    let q = new THREE.Quaternion().setFromAxisAngle(w, start * a);
    u.applyQuaternion(q).normalize();
  }
  a *= Math.abs(end - start);

  let numSteps = Math.max(1, Math.ceil((a / (2 * Math.PI)) * Daydream.W));
  let q = new THREE.Quaternion().setFromAxisAngle(w, a / numSteps);
  for (let i = 0; i <= numSteps; ++i) {
    dots.push(new Dot(u.clone(), colorFn(u, i / numSteps)));
    u.applyQuaternion(q).normalize();
  }
  return dots;
}

/**
 * Draws a set of vertices as individual dots.
 * @param {number[][]} vertices - An array of [x, y, z] arrays.
 * @param {Function} colorFn - Function to determine the color (takes vector).
 * @returns {Dot[]} An array of Dots at the vertex positions.
 */
export const drawVertices = (vertices, colorFn) => {
  let dots = [];
  let v = new THREE.Vector3();
  for (const vertex of vertices) {
    v.set(vertex[0], vertex[1], vertex[2]);
    dots.push(new Dot(v.normalize(), colorFn(v)));
  }
  return dots;
}

/**
 * Draws the edges of a polyhedron by drawing lines between connected vertices.
 * @param {number[][]} vertices - An array of [x, y, z] vertex arrays.
 * @param {number[][]} edges - An adjacency list of vertex indices.
 * @param {Function} colorFn - Function to determine the color (takes vector).
 * @returns {Dot[]} An array of Dots forming the edges.
 */
export const drawPolyhedron = (vertices, edges, colorFn) => {
  let dots = [];
  edges.map((adj, i) => {
    adj.map((j) => {
      dots = dots.concat(
        drawLine(
          new THREE.Vector3(...vertices[i]).normalize(),
          new THREE.Vector3(...vertices[j]).normalize(),
          colorFn)
      );
    })
  });
  return dots;
}

/**
 * Calculates a single point on a sphere distorted by a function, often for an oscillating ring.
 * @param {Function} f - The shift function (e.g., sinWave) based on angle.
 * @param {THREE.Vector3} normal - The normal vector defining the ring plane.
 * @param {number} radius - The base radius of the ring.
 * @param {number} angle - The angle along the ring to calculate the point.
 * @returns {THREE.Vector3} The shifted point on the sphere.
 */
export const fnPoint = (f, normal, radius, angle) => {
  let dots = [];
  let u = new THREE.Vector3();
  let v = normal.clone();
  let w = new THREE.Vector3();
  if (radius > 1) {
    v.negate();
    radius = 2 - radius;
  }
  if (Math.abs(v.dot(Daydream.X_AXIS)) > 0.99995) {
    u.crossVectors(v, Daydream.Y_AXIS).normalize();
  } else {
    u.crossVectors(v, Daydream.X_AXIS).normalize();
  }
  w.crossVectors(v, u);
  let d = Math.sqrt(Math.pow(1 - radius, 2));

  let vi = calcRingPoint(angle, radius, u, v, w);
  let vp = calcRingPoint(angle, 1, u, v, w);
  let axis = new THREE.Vector3().crossVectors(v, vp).normalize();
  let shift = new THREE.Quaternion().setFromAxisAngle(axis, f(angle * Math.PI / 2));
  return vi.clone().applyQuaternion(shift);
};

/**
 * Draws a ring that is distorted by a shift function.
 * @param {Quaternion} orientationQuaternion - The quaternion representing the global orientation.
 * @param {THREE.Vector3} normal - The base normal vector defining the ring plane.
 * @param {number} radius - The input radius (0-1) used for Equidistant spacing.
 * @param {Function} shiftFn - Function to calculate the angular shift (wave distortion).
 * @param {Function} colorFn - Function to determine the color.
 * @param {number} [phase=0] - The starting angle phase shift (unused in this specific implementation).
 * @returns {Dot[]} An array of Dots forming the distorted ring.
 */
export const drawFn = (orientationQuaternion, normal, radius, shiftFn, colorFn, phase = 0) => {
  // Basis
  let refAxis = Daydream.X_AXIS;
  if (Math.abs(normal.dot(refAxis)) > 0.9999) {
    refAxis = Daydream.Y_AXIS;
  }
  let v = normal.clone().applyQuaternion(orientationQuaternion).normalize();
  let ref = refAxis.clone().applyQuaternion(orientationQuaternion).normalize();
  let u = new THREE.Vector3().crossVectors(v, ref).normalize();
  let w = new THREE.Vector3().crossVectors(v, u).normalize();

  // Backside rings
  let vSign = 1.0;
  if (radius > 1) {
    vSign = -1.0;
    radius = 2 - radius;
  }

  // Equidistant Projection
  const thetaEq = radius * (Math.PI / 2);
  const r = Math.sin(thetaEq); 
  const d = Math.cos(thetaEq);
  let dots = [];

  let numSteps = Daydream.W;
  let from = new THREE.Vector3();
  let to = new THREE.Vector3();
  let start = new THREE.Vector3();
  let uCurrent = new THREE.Vector3();
  for (let i = 0; i < numSteps; i++) {
    let t = i / numSteps;
    // Ring step
    let theta = t * 2 * Math.PI + phase;
    let cosRing = Math.cos(theta);
    let sinRing = Math.sin(theta);
    uCurrent.copy(u).multiplyScalar(cosRing).addScaledVector(w, sinRing);

    // Rodrigues Rotation for shift
    let shift = shiftFn(t);
    let cosShift = Math.cos(shift);
    let sinShift = Math.sin(shift);
    let vScale = (vSign * d) * cosShift - r * sinShift;
    let uScale = r * cosShift + (vSign * d) * sinShift;
    to.copy(v).multiplyScalar(vScale).addScaledVector(uCurrent, uScale).normalize();

    if (i == 0) {
      start.copy(to);
    } else {
      dots.push(...drawLine(from, to, (vec, time) => colorFn(from, (i - 1) / numSteps)));
      dots.pop();
    }
    from.copy(to);
  }

  dots.push(...drawLine(from, start, (vec, time) => colorFn(from, 1)));
  dots.pop();

  return dots;
}

/**
 * Calculates a point on a circle that lies on the surface of the unit sphere.
 * Used internally by drawing functions.
 * @param {number} a - The angle in radians around the ring.
 * @param {number} radius - The ring radius in the plane.
 * @param {THREE.Vector3} u - A vector on the plane (ortho to normal).
 * @param {THREE.Vector3} v - The ring's normal (center point).
 * @param {THREE.Vector3} w - A second vector on the plane (ortho to u and normal).
 * @returns {THREE.Vector3} The normalized point on the sphere's surface.
 */
export const calcRingPoint = (a, radius, u, v, w) => {
  let d = Math.sqrt(Math.pow(1 - radius, 2));
  return new THREE.Vector3(
    d * v.x + radius * u.x * Math.cos(a) + radius * w.x * Math.sin(a),
    d * v.y + radius * u.y * Math.cos(a) + radius * w.y * Math.sin(a),
    d * v.z + radius * u.z * Math.cos(a) + radius * w.z * Math.sin(a)
  ).normalize();
}

/**
 * Draws a circular ring on the sphere surface
 * @param {Quaternion} orientationQuaternion - The quaternion representing the orientation of the ring's normal.
 * @param {THREE.Vector3} normal - The normal vector defining the ring plane.
 * @param {number} radius - The radius of the ring. Can be > 1 for a ring on the far side.
 * @param {Function} colorFn - Function to determine the color (takes vector and normalized ring angle).
 * @param {number} [phase=0] - The starting angle phase shift of the ring.
 * @returns {Dot[]} An array of Dots forming the ring.
 */
export const drawRing = (orientationQuaternion, normal, radius, colorFn, phase = 0) => {
  // Basis
  let refAxis = Daydream.X_AXIS;
  if (Math.abs(normal.dot(refAxis)) > 0.9999) {
    refAxis = Daydream.Y_AXIS;
  }
  let v = normal.clone().applyQuaternion(orientationQuaternion).normalize();
  let ref = refAxis.clone().applyQuaternion(orientationQuaternion).normalize();
  let u = new THREE.Vector3().crossVectors(v, ref).normalize();
  let w = new THREE.Vector3().crossVectors(v, u).normalize();

  // Backside rings
  let vDir = v.clone();
  if (radius > 1) {
    vDir.negate();
    radius = 2 - radius;
  }

  // Equidistant projection
  const thetaEq = radius * (Math.PI / 2); 
  const r = Math.sin(thetaEq); 
  const d = Math.cos(thetaEq);

  let dots = [];
  let numSteps = Daydream.W;
  let from = new THREE.Vector3();
  let to = new THREE.Vector3();
  let start = new THREE.Vector3();
  let uCurrent = new THREE.Vector3();

  for (let i = 0; i < numSteps; i++) {
    let t = i / numSteps;
    let theta = t * 2 * Math.PI + phase;
    let cosRing = Math.cos(theta);
    let sinRing = Math.sin(theta);
    uCurrent.copy(u).multiplyScalar(cosRing).addScaledVector(w, sinRing);
    to.copy(vDir).multiplyScalar(d).addScaledVector(uCurrent, r).normalize();

    if (i == 0) {
      start.copy(to);
    } else {
      // Draw segment between previous point and current point
      dots.push(...drawLine(from, to, (vec, time) => colorFn(from, (i - 1) / numSteps)));
      dots.pop();
    }
    from.copy(to);
  }
  dots.push(...drawLine(from, start, (vec, time) => colorFn(from, 1)));
  dots.pop();

  return dots;
}

/**
 * Calculates a single point on a circular ring on the sphere surface.
 * @param {THREE.Vector3} normal - The normal vector defining the ring plane.
 * @param {number} radius - The radius of the ring.
 * @param {number} angle - The angle around the ring's center.
 * @param {number} [phase=0] - The starting angle phase shift.
 * @returns {THREE.Vector3} The point on the sphere's surface.
 */
export const ringPoint = (normal, radius, angle, phase = 0) => {
  let dots = [];
  let u = new THREE.Vector3();
  let v = normal.clone();
  let w = new THREE.Vector3();
  if (radius > 1) {
    v.negate();
  }
  if (Math.abs(v.dot(Daydream.X_AXIS)) > 0.99995) {
    u.crossVectors(v, Daydream.Y_AXIS).normalize();
  } else {
    u.crossVectors(v, Daydream.X_AXIS).normalize();
  }
  w.crossVectors(v, u);
  if (radius > 1) {
    w.negate();
    radius = 2 - radius;
  }
  let d = Math.sqrt(Math.pow(1 - radius, 2));
  return new THREE.Vector3(
    d * v.x + radius * u.x * Math.cos(angle + phase) + radius * w.x * Math.sin(angle + phase),
    d * v.y + radius * u.y * Math.cos(angle + phase) + radius * w.y * Math.sin(angle + phase),
    d * v.z + radius * u.z * Math.cos(angle + phase) + radius * w.z * Math.sin(angle + phase)
  ).normalize();
};

/**
 * Draws points forming a Fibonacci spiral pattern.
 * @param {number} n - Total number of points.
 * @param {number} eps - Epsilon value for spiral offset.
 * @param {Function} colorFn - Function to determine the color (takes vector).
 * @returns {Dot[]} An array of Dots forming the spiral.
 */
export const drawFibSpiral = (n, eps, colorFn) => {
  let dots = [];
  for (let i = 0; i < n; ++i) {
    let v = fibSpiral(n, eps, i);
    dots.push(new Dot(v, colorFn(v)));
  }
  return dots;
};

/**
 * Plots an array of Dots onto the pixel grid using a filter.
 * @param {Map<string, THREE.Color>} pixels - The map of pixel keys to colors.
 * @param {Filter} filter - The filter chain to apply (e.g., anti-aliasing, decay).
 * @param {Dot[]} dots - The array of Dot objects to plot.
 * @param {number} age - The age parameter for filters like FilterDecay.
 * @param {number} alpha - The alpha/opacity multiplier.
 */
export function plotDots(pixels, filter, dots, age, alpha) {
  for (const dot of dots) {
    let p = sphericalToPixel(new THREE.Spherical().setFromVector3(dot.position));
    filter.plot(pixels, p.x, p.y, dot.color, age, alpha);
  }
}

/**
 * Draws a motion trail by tweening between orientations in the queue.
 * @param {Orientation} orientation - The orientation object containing the motion history.
 * @param {Function} drawFn - Function to draw a segment (takes orientation quaternion and normalized age/opacity).
 */
export const tween = (orientation, drawFn) => {
  let s = orientation.length();
  for (let i = 0; i < s; ++i) {
    drawFn(orientation.get(i), (s - 1 - i) / s);
  }
}