const enumeration = (names) => Object.fromEntries(names.map((name, value) => [name, Object.freeze({ value })]));

export const PaletteCompileCode = enumeration([
  'OK',
  'INVALID_SCHEMA',
  'NON_FINITE',
  'INVALID_ENUM',
  'HUE_LIMIT',
  'NON_INTEGER_LOOP_SWEEP',
  'INVALID_FALLOFF_START',
  'INCOMPATIBLE_OPTIONS',
]);

export const PaletteRecipeField = enumeration([
  'NONE',
  'PALETTE_DOMAIN',
  'EASING',
  'COLOR_PATH',
  'HUE_MODE',
  'HARMONY',
  'HUE_DIRECTION',
  'BASE_TURNS',
  'SPREAD_TURNS',
  'SWEEP_TURNS',
  'CUSTOM_TURNS_0',
  'CUSTOM_TURNS_1',
  'CUSTOM_TURNS_2',
  'CUSTOM_TURNS_3',
  'LIGHTNESS_CURVE',
  'LIGHTNESS_CENTER',
  'LIGHTNESS_RANGE',
  'LIGHTNESS_CUSTOM_0',
  'LIGHTNESS_CUSTOM_1',
  'LIGHTNESS_CUSTOM_2',
  'LIGHTNESS_CUSTOM_3',
  'CHROMA_CURVE',
  'CHROMA_BASIS',
  'CHROMA_CENTER',
  'CHROMA_RANGE',
  'CHROMA_CUSTOM_0',
  'CHROMA_CUSTOM_1',
  'CHROMA_CUSTOM_2',
  'CHROMA_CUSTOM_3',
  'CHROMA_HEADROOM',
  'HUE_TORSION',
  'FALLOFF_START',
  'SCHEMA_VERSION',
  'INPUT_OFFSET',
  'INPUT_SPAN',
]);
