// @ts-nocheck
//
// scripts/generate-importmap.mjs rewrites only the GENERATED VENDOR block of
// vendor-importmap.js. Driven as a subprocess against a temp fixture so the
// real repo files are never touched: the script resolves ROOT as <scriptdir>/..
// and reads package.json + vendor-importmap.js from there.
import { test, before, after } from 'node:test';
import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, rmSync, copyFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const SCRIPT_SRC = resolve(HERE, '../scripts/generate-importmap.mjs');

const PKG = JSON.stringify({
  dependencies: { three: '0.183.1', 'lil-gui': '0.21.0' },
}, null, 2);

const IMPORTMAP = [
  '(function () {',
  '  // === GENERATED by scripts/generate-importmap.mjs — do not edit by hand ===',
  "  const VENDOR = { three: 'cdn', lilGui: 'cdn' };",
  "  const THREE_VERSION = '0.0.0';",
  "  const LIL_GUI_VERSION = '0.0.0';",
  '  // === END GENERATED ===',
  '  const tail = true;',
  '})();',
  '',
].join('\n');

let root;

/** Builds a fixture repo: the script under scripts/, plus package.json and vendor-importmap.js at ROOT. */
before(() => {
  root = mkdtempSync(join(tmpdir(), 'importmap-'));
  mkdirSync(join(root, 'scripts'));
  copyFileSync(SCRIPT_SRC, join(root, 'scripts', 'generate-importmap.mjs'));
  writeFileSync(join(root, 'package.json'), PKG);
  writeFileSync(join(root, 'vendor-importmap.js'), IMPORTMAP);
});

after(() => {
  rmSync(root, { recursive: true, force: true });
});

/** Runs the fixture's script with the given args and returns the rewritten vendor-importmap.js. */
const run = (...args) => {
  writeFileSync(join(root, 'vendor-importmap.js'), IMPORTMAP);
  execFileSync(process.execPath, [join(root, 'scripts', 'generate-importmap.mjs'), ...args]);
  return readFileSync(join(root, 'vendor-importmap.js'), 'utf8');
};

/** Places the vendored entry points the --local probes require under ROOT. */
const vendorLocal = () => {
  mkdirSync(join(root, 'three.js', 'build'), { recursive: true });
  writeFileSync(join(root, 'three.js', 'build', 'three.module.js'), '');
  mkdirSync(join(root, 'node_modules', 'lil-gui', 'dist'), { recursive: true });
  writeFileSync(join(root, 'node_modules', 'lil-gui', 'dist', 'lil-gui.esm.min.js'), '');
};

/** Verifies the default (no-flag) run bakes an all-CDN VENDOR block with the package.json versions. */
test('default mode rewrites the VENDOR block to all-cdn with pinned versions', () => {
  const out = run();
  assert.match(out, /const VENDOR = \{ three: 'cdn', lilGui: 'cdn' \};/);
  assert.match(out, /const THREE_VERSION = '0\.183\.1';/);
  assert.match(out, /const LIL_GUI_VERSION = '0\.21\.0';/);
  // The non-generated body is preserved.
  assert.ok(out.includes('const tail = true;'));
});

/** Verifies --local resolves each library to 'local' only when its vendored entry point exists. */
test('--local mode bakes local resolution when the entry points are present', () => {
  vendorLocal();
  const out = run('--local');
  assert.match(out, /const VENDOR = \{ three: 'local', lilGui: 'local' \};/);
});

/** Verifies --local falls back to cdn for a library whose entry point is missing. */
test('--local falls back to cdn when an entry point is absent', () => {
  // No vendored files placed for this fresh run (after() of the prior test left
  // them, so rebuild the fixture root clean here).
  rmSync(root, { recursive: true, force: true });
  mkdirSync(join(root, 'scripts'), { recursive: true });
  copyFileSync(SCRIPT_SRC, join(root, 'scripts', 'generate-importmap.mjs'));
  writeFileSync(join(root, 'package.json'), PKG);
  const out = run('--local');
  assert.match(out, /const VENDOR = \{ three: 'cdn', lilGui: 'cdn' \};/);
});
